### ISSUE TITLE
Can't Figure out dependencies 

### ISSUE THREAD

**Issue by Bobthekingdom** [xMGZx/mdrpmc#2]
So that every time I put the mod in since I have to hand type it I checked it and it is correct I don't know how to add dependencies

**Comment by Bobthekingdom** [comment]
Nevermind

**Comment by mathgeniuszach** [comment]
![image](https://user-images.githubusercontent.com/40220050/117596437-6317da00-b111-11eb-855c-40a7843f0aa2.png)
It's on the front page. Some mods (like OptiFine) don't register themselves as mods. Forge and Fabric have special formats for version, like `>=` or `[)`. Do not include spaces and make sure everything is lowercase. No further help can be given.

**Comment by Bobthekingdom** [comment]
sorry i am a idiot
